FROM node:22-alpine AS build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend ./
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist/saas-system-angular /usr/share/nginx/html
COPY devops/docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
